### ISSUE TITLE
Styles and scripts are not loaded over HTTPS

### ISSUE THREAD

**Issue by tfausak** [kcsongor/kcsongor.github.io#1]
When I try to view your blog over HTTPS none of the styles or scripts load. https://kcsongor.github.io

![screen shot 2018-02-26 at 8 09 33 am](https://user-images.githubusercontent.com/408753/36672190-67ee72c0-1acc-11e8-93e3-8144c6d503ab.png)

**Comment by kcsongor** [comment]
Thanks for reporting this! I will try to fix it, provided that I manage to work out how Jekyll generates these URLs.

**Comment by kcsongor** [comment]
@plietar any ideas?

**Comment by kcsongor** [comment]
Turns out this was a simple fix!
